name: Archive Private Repos to Azure

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"   # Runs at 03:00, only on Friday.

permissions:
  contents: write
  actions: write
  id-token: write

jobs:
  archive:
    runs-on: windows-latest
    environment: production
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Az PowerShell modules
        run: |
          Install-Module -Name Az.Accounts -Force -Scope CurrentUser
          Install-Module -Name Az.Storage -Force -Scope CurrentUser

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Create Token
        id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ARCHIVE_APP_ID }}
          private_key: ${{ secrets.ARCHIVE_APP_PRIVATE_KEY }}

      - name: Archive selected private repos
        run: |
          pwsh ./archive-private-repos.ps1 `
            -GitHubOrg ${{ github.repository_owner }} `
            -GitHubToken ${{ steps.create_token.outputs.token }} `
            -StorageAccountName ${{ secrets.AZURE_STORAGE_ACCOUNT }} `
            -StorageAccountKey ${{ secrets.AZURE_STORAGE_KEY }} `
            -ContainerName ${{ vars.CONTAINER_NAME }}
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
