name: Archive Private Repos to Azure

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"   # Runs at 03:00, only on Friday.

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
  GIT_HUB_ORG: ${{ secrets.GIT_HUB_ORG }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

jobs:
  archive:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Az PowerShell modules
        run: |
          Install-Module -Name Az.Accounts -Force -Scope CurrentUser
          Install-Module -Name Az.Storage -Force -Scope CurrentUser

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Archive selected private repos
        run: |
          pwsh ./archive-private-repos.ps1 `
            -GitHubOrg ${{ env.GIT_HUB_ORG }} `
            -GitHubToken ${{ secrets.GITHUB_TOKEN }} `
            -StorageAccountName ${{ env.AZURE_STORAGE_ACCOUNT }} `
            -StorageAccountKey ${{ env.AZURE_STORAGE_KEY }} `
            -ContainerName ${{ env.CONTAINER_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
