name: Archive Private Repos to Azure

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"   # Runs at 03:00, only on Friday.

jobs:
  archive:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Az PowerShell modules
        run: |
          Install-Module -Name Az.Accounts -Force -Scope CurrentUser
          Install-Module -Name Az.Storage -Force -Scope CurrentUser

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Archive selected private repos
        run: |
          pwsh ./archive-private-repos.ps1 `
            -GitHubOrg ${{ vars.GIT_HUB_ORG }} `
            -GitHubToken ${{ secrets.GITHUB_TOKEN }} `
            -StorageAccountName ${{ vars.AZURE_STORAGE_ACCOUNT }} `
            -StorageAccountKey ${{ secrets.AZURE_STORAGE_KEY }} `
            -ContainerName ${{ vars.CONTAINER_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
